### ISSUE TITLE
host node component

### ISSUE THREAD

**Issue by mightgoyardstill** [hkarim/JUCE-Graph-Component#2]
this is more of a question rather than issue,

i'm trying to adapt your example for a project of mine and i'm getting a bit lost understanding what each component does (in particular the host component).

would it be possible to request some commentary in the source code that briefly explains what each file is actually doing? it's quite overwhelming to understand as a new comer!

**Comment by mightgoyardstill** [comment]
in particular for my case i'm trying to understand if the host component is essentially a nested window? where editor is essentially whatever you want to put in this component?

and guest seems to be a method of editor which retrieves whatever is in editor??

**Comment by hkarim** [comment]
@mightgoyardstill Sorry for the late reply. I hadn't touch this code in years, but if I remember correctly, the host component allows hosting any JUCE component so, it will be available inside the graph editor.

**Comment by hkarim** [comment]
@mightgoyardstill Please see the new implementation on the `main` branch. It has exactly what you described
